// Generated by gencpp from file ground_projection/GetGroundCoordRequest.msg
// DO NOT EDIT!


#ifndef GROUND_PROJECTION_MESSAGE_GETGROUNDCOORDREQUEST_H
#define GROUND_PROJECTION_MESSAGE_GETGROUNDCOORDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <duckietown_msgs/Vector2D.h>

namespace ground_projection
{
template <class ContainerAllocator>
struct GetGroundCoordRequest_
{
  typedef GetGroundCoordRequest_<ContainerAllocator> Type;

  GetGroundCoordRequest_()
    : normalized_uv()  {
    }
  GetGroundCoordRequest_(const ContainerAllocator& _alloc)
    : normalized_uv(_alloc)  {
    }



   typedef  ::duckietown_msgs::Vector2D_<ContainerAllocator>  _normalized_uv_type;
  _normalized_uv_type normalized_uv;




  typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGroundCoordRequest_

typedef ::ground_projection::GetGroundCoordRequest_<std::allocator<void> > GetGroundCoordRequest;

typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest > GetGroundCoordRequestPtr;
typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest const> GetGroundCoordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ground_projection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'duckietown_msgs': ['/home/ubuntu/duckietown/catkin_ws/src/duckietown_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e079b9787496ba75117334836e96c45";
  }

  static const char* value(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e079b9787496ba7ULL;
  static const uint64_t static_value2 = 0x5117334836e96c45ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_projection/GetGroundCoordRequest";
  }

  static const char* value(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
duckietown_msgs/Vector2D normalized_uv\n\
\n\
================================================================================\n\
MSG: duckietown_msgs/Vector2D\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.normalized_uv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetGroundCoordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>& v)
  {
    s << indent << "normalized_uv: ";
    s << std::endl;
    Printer< ::duckietown_msgs::Vector2D_<ContainerAllocator> >::stream(s, indent + "  ", v.normalized_uv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_PROJECTION_MESSAGE_GETGROUNDCOORDREQUEST_H
