// Generated by gencpp from file duckietown_msgs/KinematicsParameters.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_KINEMATICSPARAMETERS_H
#define DUCKIETOWN_MSGS_MESSAGE_KINEMATICSPARAMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct KinematicsParameters_
{
  typedef KinematicsParameters_<ContainerAllocator> Type;

  KinematicsParameters_()
    : parameters()  {
    }
  KinematicsParameters_(const ContainerAllocator& _alloc)
    : parameters(_alloc)  {
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _parameters_type;
  _parameters_type parameters;




  typedef boost::shared_ptr< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicsParameters_

typedef ::duckietown_msgs::KinematicsParameters_<std::allocator<void> > KinematicsParameters;

typedef boost::shared_ptr< ::duckietown_msgs::KinematicsParameters > KinematicsParametersPtr;
typedef boost::shared_ptr< ::duckietown_msgs::KinematicsParameters const> KinematicsParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/home/ubuntu/duckietown/catkin_ws/src/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbca57679564ab84ca723072e3bf6226";
  }

  static const char* value(const ::duckietown_msgs::KinematicsParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbca57679564ab84ULL;
  static const uint64_t static_value2 = 0xca723072e3bf6226ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/KinematicsParameters";
  }

  static const char* value(const ::duckietown_msgs::KinematicsParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] parameters\n\
";
  }

  static const char* value(const ::duckietown_msgs::KinematicsParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct KinematicsParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::KinematicsParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::KinematicsParameters_<ContainerAllocator>& v)
  {
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_KINEMATICSPARAMETERS_H
