// Generated by gencpp from file imu_test/angular.msg
// DO NOT EDIT!


#ifndef IMU_TEST_MESSAGE_ANGULAR_H
#define IMU_TEST_MESSAGE_ANGULAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_test
{
template <class ContainerAllocator>
struct angular_
{
  typedef angular_<ContainerAllocator> Type;

  angular_()
    : roll(0.0)
    , pitch(0.0)  {
    }
  angular_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)  {
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;




  typedef boost::shared_ptr< ::imu_test::angular_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_test::angular_<ContainerAllocator> const> ConstPtr;

}; // struct angular_

typedef ::imu_test::angular_<std::allocator<void> > angular;

typedef boost::shared_ptr< ::imu_test::angular > angularPtr;
typedef boost::shared_ptr< ::imu_test::angular const> angularConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_test::angular_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_test::angular_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/home/ubuntu/duckietown/catkin_ws/src/duckietown_msgs/msg'], 'imu_test': ['/home/ubuntu/duckietown/catkin_ws/src/arg_nctu/sean/imu_test/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_test::angular_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_test::angular_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_test::angular_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_test::angular_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_test::angular_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_test::angular_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_test::angular_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c482a7bc02c0a82e3b3c8330e20ac46d";
  }

  static const char* value(const ::imu_test::angular_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc482a7bc02c0a82eULL;
  static const uint64_t static_value2 = 0x3b3c8330e20ac46dULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_test::angular_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_test/angular";
  }

  static const char* value(const ::imu_test::angular_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_test::angular_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n\
float32 pitch\n\
";
  }

  static const char* value(const ::imu_test::angular_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_test::angular_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct angular_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_test::angular_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_test::angular_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_TEST_MESSAGE_ANGULAR_H
