# Initail state of the FSM
initial_state: "APPLE"

events: #Maps from subscribing topic to signal ids
  pressX:
    topic: "joy_mapper_node/pub_X"
    msg_type: "BoolStamped"
    trigger: True
  pressY:
    topic: "joy_mapper_node/pub_Y"
    msg_type: "BoolStamped"
    trigger: True
  pressA: 
    topic: "joy_mapper_node/pub_A"
    msg_type: "BoolStamped"
    trigger: False
  pressB: 
    topic: "joy_mapper_node/pub_B"
    msg_type: "BoolStamped"
    trigger: True

# Define nodes 
nodes:
  stop_line_filter_node: "stop_line_filter_node/switch"
  lane_filter_node: "lane_filter_node/switch"

# Define state transitions
states:
  APPLE:
    transitions:
      pressB: "BANANA"
      pressA: "ORANGE"
    active_nodes:
      - stop_line_filter_node
      - lane_filter_node

  BANANA:
    transitions:
      pressX: "APPLE"
      pressY: "ORANGE"
    active_nodes:
      - lane_filter_node

  ORANGE:
    transitions:
      pressB: "BANANA"
      pressY: "APPLE"
    active_nodes:
      - stop_line_filter_node
