# Initail state of the FSM`
initial_state: "idle"
   
events: #Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  switchoffArduino:
    topic: "arduino_node/turnoffarduino"  
    msg_type: "BoolStamped"
    trigger: True
  Stop_Red_Line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True      
  Collected_Medication: 
    topic: "arduino_node/changetolanefollow"
    msg_type: "BoolStamped"
    trigger: True
  Not_Time_Yet:
    topic: "arduino_node/goback"
    msg_type: "BoolStamped"
    trigger: True
  SwitchoffApril:
    topic: "arduino_node/turnoffapril"
    msg_type: "BoolStamped"
    trigger: True

global_transitions:
  joystick_override_on: "idle"

# Define nodes 
nodes:
  line_detector_node: "line_detector_node/switch"
  lane_following_node: "lane_following_node/switch"
  joy_mapper_node: "joy_mapper_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  arduino_node: "arduino_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  lane_detector_node : "lane_detector_node/switch"
  decoder_node: "decoder_node/switch"
  #anti_instagram_node: "anti_instagram/switch"
  apriltag_node: "apriltag_detector_node/switch"
  vehicle_detector_node: "vehicle_detection_node/switch"
  led_detector_node: "LED_detector_node/switch"
  led_emitter_node: "led_emitter_node/switch"
  static_object_detector_node: "static_object_detector_node/switch"
  framerate_high: "camera_node/framerate_high_switch"

# Define state transitions
states:
  idle:
    transitions:
      joystick_override_off: "LANE_FOLLOWING"
    active_nodes:
      - joy_mapper_node
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - framerate_high

  LANE_FOLLOWING:
    transitions:
      Stop_Red_Line: "DispensationMode"
    active_nodes:
      - lane_filter_node
      - stop_line_filter_node
      - line_detector_node
      - decoder_node

  DispensationMode:
    transitions:
      Not_Time_Yet: "LANE_FOLLOWING"
      SwitchoffApril: "ArduinoMode"
      switchoffArduino: "idle"
    active_nodes:
      - arduino_node
      - apriltag_node
      - decoder_node

  ArduinoMode:
    transitions:
      Collected_Medication: "LANE_FOLLOWING"
    active_nodes:
      - arduino_node
