// Generated by gencpp from file scene_segmentation/SegmentImage.msg
// DO NOT EDIT!


#ifndef SCENE_SEGMENTATION_MESSAGE_SEGMENTIMAGE_H
#define SCENE_SEGMENTATION_MESSAGE_SEGMENTIMAGE_H

#include <ros/service_traits.h>


#include <scene_segmentation/SegmentImageRequest.h>
#include <scene_segmentation/SegmentImageResponse.h>


namespace scene_segmentation
{

struct SegmentImage
{

typedef SegmentImageRequest Request;
typedef SegmentImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SegmentImage
} // namespace scene_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scene_segmentation::SegmentImage > {
  static const char* value()
  {
    return "f507632f63ad609c9a8e01b0f4807734";
  }

  static const char* value(const ::scene_segmentation::SegmentImage&) { return value(); }
};

template<>
struct DataType< ::scene_segmentation::SegmentImage > {
  static const char* value()
  {
    return "scene_segmentation/SegmentImage";
  }

  static const char* value(const ::scene_segmentation::SegmentImage&) { return value(); }
};


// service_traits::MD5Sum< ::scene_segmentation::SegmentImageRequest> should match 
// service_traits::MD5Sum< ::scene_segmentation::SegmentImage > 
template<>
struct MD5Sum< ::scene_segmentation::SegmentImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scene_segmentation::SegmentImage >::value();
  }
  static const char* value(const ::scene_segmentation::SegmentImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scene_segmentation::SegmentImageRequest> should match 
// service_traits::DataType< ::scene_segmentation::SegmentImage > 
template<>
struct DataType< ::scene_segmentation::SegmentImageRequest>
{
  static const char* value()
  {
    return DataType< ::scene_segmentation::SegmentImage >::value();
  }
  static const char* value(const ::scene_segmentation::SegmentImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scene_segmentation::SegmentImageResponse> should match 
// service_traits::MD5Sum< ::scene_segmentation::SegmentImage > 
template<>
struct MD5Sum< ::scene_segmentation::SegmentImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scene_segmentation::SegmentImage >::value();
  }
  static const char* value(const ::scene_segmentation::SegmentImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scene_segmentation::SegmentImageResponse> should match 
// service_traits::DataType< ::scene_segmentation::SegmentImage > 
template<>
struct DataType< ::scene_segmentation::SegmentImageResponse>
{
  static const char* value()
  {
    return DataType< ::scene_segmentation::SegmentImage >::value();
  }
  static const char* value(const ::scene_segmentation::SegmentImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCENE_SEGMENTATION_MESSAGE_SEGMENTIMAGE_H
