// Generated by gencpp from file duckietown_kaku/gripper_modeFeedback.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_KAKU_MESSAGE_GRIPPER_MODEFEEDBACK_H
#define DUCKIETOWN_KAKU_MESSAGE_GRIPPER_MODEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_kaku
{
template <class ContainerAllocator>
struct gripper_modeFeedback_
{
  typedef gripper_modeFeedback_<ContainerAllocator> Type;

  gripper_modeFeedback_()
    : distance(0.0)  {
    }
  gripper_modeFeedback_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
    }



   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct gripper_modeFeedback_

typedef ::duckietown_kaku::gripper_modeFeedback_<std::allocator<void> > gripper_modeFeedback;

typedef boost::shared_ptr< ::duckietown_kaku::gripper_modeFeedback > gripper_modeFeedbackPtr;
typedef boost::shared_ptr< ::duckietown_kaku::gripper_modeFeedback const> gripper_modeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_kaku

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'duckietown_kaku': ['/home/ubuntu/duckietown/catkin_ws/devel/share/duckietown_kaku/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_kaku/gripper_modeFeedback";
  }

  static const char* value(const ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 distance \n\
\n\
";
  }

  static const char* value(const ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct gripper_modeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_kaku::gripper_modeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_KAKU_MESSAGE_GRIPPER_MODEFEEDBACK_H
