// Generated by gencpp from file duckietown_kaku/path_followingGoal.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_KAKU_MESSAGE_PATH_FOLLOWINGGOAL_H
#define DUCKIETOWN_KAKU_MESSAGE_PATH_FOLLOWINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace duckietown_kaku
{
template <class ContainerAllocator>
struct path_followingGoal_
{
  typedef path_followingGoal_<ContainerAllocator> Type;

  path_followingGoal_()
    : waypoints()  {
    }
  path_followingGoal_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _waypoints_type;
  _waypoints_type waypoints;




  typedef boost::shared_ptr< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct path_followingGoal_

typedef ::duckietown_kaku::path_followingGoal_<std::allocator<void> > path_followingGoal;

typedef boost::shared_ptr< ::duckietown_kaku::path_followingGoal > path_followingGoalPtr;
typedef boost::shared_ptr< ::duckietown_kaku::path_followingGoal const> path_followingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_kaku::path_followingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_kaku

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'duckietown_kaku': ['/home/ubuntu/duckietown/catkin_ws/devel/share/duckietown_kaku/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea70e23febd08605663de4b49bc50398";
  }

  static const char* value(const ::duckietown_kaku::path_followingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea70e23febd08605ULL;
  static const uint64_t static_value2 = 0x663de4b49bc50398ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_kaku/path_followingGoal";
  }

  static const char* value(const ::duckietown_kaku::path_followingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
geometry_msgs/PoseArray waypoints \n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::duckietown_kaku::path_followingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct path_followingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_kaku::path_followingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_kaku::path_followingGoal_<ContainerAllocator>& v)
  {
    s << indent << "waypoints: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_KAKU_MESSAGE_PATH_FOLLOWINGGOAL_H
