; Auto-generated. Do not edit!


(cl:in-package duckietown_kaku-msg)


;//! \htmlinclude gripper_modeGoal.msg.html

(cl:defclass <gripper_modeGoal> (roslisp-msg-protocol:ros-message)
  ((object_point
    :reader object_point
    :initarg :object_point
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass gripper_modeGoal (<gripper_modeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <gripper_modeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'gripper_modeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name duckietown_kaku-msg:<gripper_modeGoal> is deprecated: use duckietown_kaku-msg:gripper_modeGoal instead.")))

(cl:ensure-generic-function 'object_point-val :lambda-list '(m))
(cl:defmethod object_point-val ((m <gripper_modeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader duckietown_kaku-msg:object_point-val is deprecated.  Use duckietown_kaku-msg:object_point instead.")
  (object_point m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <gripper_modeGoal>) ostream)
  "Serializes a message object of type '<gripper_modeGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_point) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <gripper_modeGoal>) istream)
  "Deserializes a message object of type '<gripper_modeGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_point) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<gripper_modeGoal>)))
  "Returns string type for a message object of type '<gripper_modeGoal>"
  "duckietown_kaku/gripper_modeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'gripper_modeGoal)))
  "Returns string type for a message object of type 'gripper_modeGoal"
  "duckietown_kaku/gripper_modeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<gripper_modeGoal>)))
  "Returns md5sum for a message object of type '<gripper_modeGoal>"
  "7b6fe603b1bb4c161f7386b63ba5c0ae")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'gripper_modeGoal)))
  "Returns md5sum for a message object of type 'gripper_modeGoal"
  "7b6fe603b1bb4c161f7386b63ba5c0ae")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<gripper_modeGoal>)))
  "Returns full string definition for message of type '<gripper_modeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Point object_point ~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'gripper_modeGoal)))
  "Returns full string definition for message of type 'gripper_modeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Point object_point ~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <gripper_modeGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_point))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <gripper_modeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'gripper_modeGoal
    (cl:cons ':object_point (object_point msg))
))
