; Auto-generated. Do not edit!


(cl:in-package duckietown_kaku-msg)


;//! \htmlinclude gripper_grabGoal.msg.html

(cl:defclass <gripper_grabGoal> (roslisp-msg-protocol:ros-message)
  ((grasping_state
    :reader grasping_state
    :initarg :grasping_state
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass gripper_grabGoal (<gripper_grabGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <gripper_grabGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'gripper_grabGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name duckietown_kaku-msg:<gripper_grabGoal> is deprecated: use duckietown_kaku-msg:gripper_grabGoal instead.")))

(cl:ensure-generic-function 'grasping_state-val :lambda-list '(m))
(cl:defmethod grasping_state-val ((m <gripper_grabGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader duckietown_kaku-msg:grasping_state-val is deprecated.  Use duckietown_kaku-msg:grasping_state instead.")
  (grasping_state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <gripper_grabGoal>) ostream)
  "Serializes a message object of type '<gripper_grabGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'grasping_state) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <gripper_grabGoal>) istream)
  "Deserializes a message object of type '<gripper_grabGoal>"
    (cl:setf (cl:slot-value msg 'grasping_state) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<gripper_grabGoal>)))
  "Returns string type for a message object of type '<gripper_grabGoal>"
  "duckietown_kaku/gripper_grabGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'gripper_grabGoal)))
  "Returns string type for a message object of type 'gripper_grabGoal"
  "duckietown_kaku/gripper_grabGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<gripper_grabGoal>)))
  "Returns md5sum for a message object of type '<gripper_grabGoal>"
  "368ca60bbb64323101f6a10f41ef8495")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'gripper_grabGoal)))
  "Returns md5sum for a message object of type 'gripper_grabGoal"
  "368ca60bbb64323101f6a10f41ef8495")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<gripper_grabGoal>)))
  "Returns full string definition for message of type '<gripper_grabGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%bool grasping_state ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'gripper_grabGoal)))
  "Returns full string definition for message of type 'gripper_grabGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%bool grasping_state ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <gripper_grabGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <gripper_grabGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'gripper_grabGoal
    (cl:cons ':grasping_state (grasping_state msg))
))
