; Auto-generated. Do not edit!


(cl:in-package duckietown_kaku-msg)


;//! \htmlinclude path_followingFeedback.msg.html

(cl:defclass <path_followingFeedback> (roslisp-msg-protocol:ros-message)
  ((waypoint_index
    :reader waypoint_index
    :initarg :waypoint_index
    :type cl:integer
    :initform 0))
)

(cl:defclass path_followingFeedback (<path_followingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <path_followingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'path_followingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name duckietown_kaku-msg:<path_followingFeedback> is deprecated: use duckietown_kaku-msg:path_followingFeedback instead.")))

(cl:ensure-generic-function 'waypoint_index-val :lambda-list '(m))
(cl:defmethod waypoint_index-val ((m <path_followingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader duckietown_kaku-msg:waypoint_index-val is deprecated.  Use duckietown_kaku-msg:waypoint_index instead.")
  (waypoint_index m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <path_followingFeedback>) ostream)
  "Serializes a message object of type '<path_followingFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'waypoint_index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'waypoint_index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'waypoint_index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'waypoint_index)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <path_followingFeedback>) istream)
  "Deserializes a message object of type '<path_followingFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'waypoint_index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'waypoint_index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'waypoint_index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'waypoint_index)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<path_followingFeedback>)))
  "Returns string type for a message object of type '<path_followingFeedback>"
  "duckietown_kaku/path_followingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'path_followingFeedback)))
  "Returns string type for a message object of type 'path_followingFeedback"
  "duckietown_kaku/path_followingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<path_followingFeedback>)))
  "Returns md5sum for a message object of type '<path_followingFeedback>"
  "5c1cf10c0f9fbb21a09c9f5f1d826929")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'path_followingFeedback)))
  "Returns md5sum for a message object of type 'path_followingFeedback"
  "5c1cf10c0f9fbb21a09c9f5f1d826929")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<path_followingFeedback>)))
  "Returns full string definition for message of type '<path_followingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint32 waypoint_index~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'path_followingFeedback)))
  "Returns full string definition for message of type 'path_followingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint32 waypoint_index~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <path_followingFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <path_followingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'path_followingFeedback
    (cl:cons ':waypoint_index (waypoint_index msg))
))
